# Generated by Django 3.2.9 on 2021-11-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TexFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='texfiles')),
                ('image', models.ImageField(upload_to='texfiles')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
