# Generated by Django 3.2 on 2021-12-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texfiles', '0002_auto_20211204_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='texfile',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
