# Generated by Django 3.2 on 2021-12-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texfiles', '0004_alter_texfile_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texfile',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
