# Generated by Django 3.2.9 on 2021-12-01 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('max_of_rows', models.SmallIntegerField(default=12)),
                ('max_of_columns', models.SmallIntegerField(default=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverletters', to='sessions.session')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='session key')),
                ('session_data', models.TextField(verbose_name='session data')),
                ('expire_date', models.DateTimeField(db_index=True, verbose_name='expire date')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='coverletters.coverletter')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('row_position', models.SmallIntegerField(null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coverletters.column')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coverletters.row')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag', to='coverletters.column')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='coverletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='coverletters.coverletter'),
        ),
    ]
