# Generated by Django 3.2.9 on 2021-11-29 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('number_of_item_rows', models.SmallIntegerField(default=5)),
                ('max_of_rows', models.SmallIntegerField(default=12)),
                ('max_of_columns', models.SmallIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='coverletters.coverletter')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('row_position', models.SmallIntegerField(null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coverletters.column')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coverletters.row')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag', to='coverletters.column')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='coverletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='coverletters.coverletter'),
        ),
    ]
