# Generated by Django 3.2.9 on 2021-11-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='sessionid',
            field=models.CharField(default='adfadadadsadf', max_length=64),
            preserve_default=False,
        ),
    ]
