# Generated by Django 3.2.9 on 2021-11-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverletter',
            old_name='body',
            new_name='text',
        ),
    ]
