# Generated by Django 3.2.9 on 2021-11-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0002_rename_body_coverletter_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='coverletter',
            name='number_of_hashtags',
            field=models.SmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='number_of_items',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='coverletters.hashtag')),
            ],
        ),
        migrations.AddField(
            model_name='hashtag',
            name='coverletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='coverletters.coverletter'),
        ),
    ]
