# Generated by Django 3.2.9 on 2021-11-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0003_auto_20211126_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='number_of_hashtags',
        ),
    ]
