# Generated by Django 3.2.9 on 2021-12-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0004_coverletter_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='applying_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
