# Generated by Django 3.2.9 on 2021-11-27 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0004_remove_coverletter_number_of_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='coverletters.hashtag'),
        ),
    ]
