# Generated by Django 3.2.9 on 2021-11-30 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0005_alter_coverletter_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='sessionid',
        ),
    ]
