# Generated by Django 3.2.9 on 2021-12-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0005_coverletter_applying_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSession',
        ),
        migrations.AddField(
            model_name='row',
            name='position',
            field=models.SmallIntegerField(default=12),
        ),
    ]
