# Generated by Django 3.2.9 on 2021-11-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0005_alter_item_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coverletter',
            old_name='number_of_items',
            new_name='number_of_item_rows',
        ),
    ]
