# Generated by Django 3.2.9 on 2021-11-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0006_remove_coverletter_sessionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='number_of_item_rows',
        ),
    ]
