# Generated by Django 3.2.9 on 2021-11-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0006_rename_number_of_items_coverletter_number_of_item_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='row_position',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='number_of_item_rows',
            field=models.SmallIntegerField(default=3),
        ),
    ]
