# Generated by Django 3.2.9 on 2021-12-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0007_alter_row_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
