# Generated by Django 3.2.9 on 2021-11-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0007_auto_20211127_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='max_hastags',
            field=models.SmallIntegerField(default=10),
        ),
    ]
