# Generated by Django 3.2.9 on 2021-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0008_coverletter_max_hastags'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='max_item_rows',
            field=models.SmallIntegerField(default=12),
        ),
    ]
