# Generated by Django 3.2.9 on 2021-12-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0009_alter_row_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='row_position',
        ),
        migrations.RemoveField(
            model_name='row',
            name='position',
        ),
    ]
