# Generated by Django 3.2.9 on 2021-12-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texfiles', '0002_auto_20211204_0940'),
        ('coverletters', '0012_coverletter_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='selected_texfile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texfiles.texfile'),
        ),
    ]
