# Generated by Django 3.2 on 2021-12-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0014_remove_coverletter_selected_texfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='max_of_rows',
            field=models.SmallIntegerField(default=50),
        ),
    ]
