# Generated by Django 3.2 on 2021-12-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texfiles', '0005_alter_texfile_downloads'),
        ('coverletters', '0015_alter_coverletter_max_of_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='tex_file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texfiles.texfile'),
        ),
    ]
