# Generated by Django 3.2 on 2021-12-15 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('texfiles', '0005_alter_texfile_downloads'),
        ('coverletters', '0016_coverletter_tex_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='tex_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texfiles.texfile'),
        ),
    ]
