# Generated by Django 3.2 on 2021-12-16 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0017_alter_coverletter_tex_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='created_on',
        ),
        migrations.AddField(
            model_name='coverletter',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coverletter',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
