# Generated by Django 3.2 on 2021-12-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coverletters', '0018_auto_20211216_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
